### ISSUE TITLE
💡

### ISSUE THREAD

**Issue by mittan12** [TinyKitten/StationAPI#1070]
## 概要
プロジェクトに対して感じている課題やご要望をなるべく詳細にご記入ください

## 想定されている解決策
上記課題に対する解決策がございましたらご記入ください

## スクリーンショット
スクリーンショット等このチケットに関連する画像を任意で添付してください

## その他
その他課題・ご要望に関して追加の情報がございましたらご記入ください

**Comment by 10mocy** [comment]
@mittan12 
詳細情報の記載をお願いします。
間違って作成した場合は close してください。

**Comment by mittan12** [comment]
おそらく誤って作成されたものだと思われます。
